name: Release branch check
on:
  push:
    branches:
      - release-**v[0-9]+.[0-9]+.[0-9]+ # client
      - release-**v[0-9]+               # runtimes
      - polkadot-v[0-9]+.[0-9]+.[0-9]+  # cumulus code

  workflow_dispatch:

jobs:
  check_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
        with:
          fetch-depth: 0

      - name: Run check
        shell: bash
        run: ./scripts/ci/github/check-rel-br
